### ISSUE TITLE
Usage Example

### ISSUE THREAD

**Issue by stefanfrede** [Collaborne/iron-socket-io-client#1]
It would be nice to have an example how to use the component, sadly I can't figure it out.

**Comment by scenaristeur** [comment]
Yes I need help too using nodejs with express & socket and a 'public' folder, I don't know what is the right way to import Polymer library and other components like that : 

- root 
       | - index.js (server with socket.io & app.use(express.static(__dirname + '/public'));
       | - public 
                | - index.html
                | - src
                       | - my-app
                                    | - my-app.html
                       | - first-element
                                    | - first-element.html


There was no probleme with Polymer 2 (i've developped many apps https://github.com/scenaristeur/heroku-spoggy)  but we can't use ' <link rel="import" href="../../bower_components/polymer/polymer-element.html">' anymore, so could you tell me what is the way to import Polymer 3 library and other components with nodejs, socket.io in this config ?

Thanks

**Comment by stefanfrede** [comment]
I figured out my initial question quite a while ago. I guess the P3 problem belongs into an issue of its own. Therefore I close this issue.
