### ISSUE TITLE
'error' event should be handled properly

### ISSUE THREAD

**Issue by ankon** [Collaborne/iron-socket-io-client#5]
Right now the component simply logs the 'error' event contents to the console, and then assumes everything will be fine.

That is not the case, or at least not always: a `TransportError` for example seems to mean that the connection is completely broken, and we should do something.

I think what would be ok is:
1. Add and expose an `error` state
2. Somehow expose the actual errors (through a custom event?)
3. Document that the user should monitor for `error`, and then do something to recover (reconnect, communicate to the humans, ...)

**Comment by ronnyroeller** [comment]
Line in question: https://github.com/Collaborne/iron-socket-io-client/blob/master/iron-socket-io-client.html#L122
